Comisionesv2/WebApplication1/Models/clienteVendedor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class clienteVendedor
    {
        public int idEmpresa { get; set; }
        public string idCliente { get; set; }
        public string strNombreCliente { get; set; }
        public int intDiasCredito { get; set; }
        public int intDiasRetencion { get; set; }
        public int intDiasGracia { get; set; }
        public int idCodigoVendedor { get; set; }
        public string nombreVendedor { get; set; }
    }
}

Comisionesv2/WebApplication1/Controllers/ConsultasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OneCoreData;
using WebApplication1.Models;
using System.Data.Entity.Validation;
using WebApplication1.Utilidades;
using System.Data.SqlClient;

namespace WebApplication1.Controllers
{
    public class ConsultasController : Controller
    {
        private COMISIONESEntities db = new COMISIONESEntities();

        // GET: Consultas
        public ActionResult Consultas()
        {
            if (Session["RolID"] == null)
            {
                return View("~/Views/Home/Login.cshtml");
            }
            else
            {
                if (Session["RolID"].Equals("Administrador") || Session["RolID"].Equals("Operador") || Session["RolID"].Equals("Vendedor"))
                {
                    //ViewBag.IdEmpresa = new SelectList(db.com_empresas, "IdEmpresa", "strNombreEmpresa");
                    //ViewBag.idCodigoVendedor = new SelectList(db.com_vendedores.Where(p => p.boolActivo == true), "idCodigoVendedor", "strNombre");
                    //var com_clientesComConfig = db.com_clientesComConfig.Where(p => p.boolActivo == true).Include(c => c.com_empresas).Include(c => c.com_vendedores);
                    //ViewBag.hdnRolID = Session["RolID"].ToString();
                    if (!Session["RolID"].Equals("Vendedor"))
                    {
                        ViewBag.BagVendedores = new SelectList(ListaPersonalizadaVendedores(), "Value", "Text");
                    }
                    else
                    {
                        ViewBag.BagVendedores = new SelectList(ListaPersonalizadaVendedor(), "Value", "Text");
                    }
                    List<SelectListItem> newList = new List<SelectListItem>();

                    SelectListItem ListaItemPeriodos = new SelectListItem();
                    //ListaItemPeriodos = new SelectListItem { Text = "", Value = "" };
                    //newList.Add(ListaItemPeriodos);


                    SelectListItem ListaItemsPeriodos = new SelectListItem();
                    for (int i = 0; i < 99; i++)
                    {
                        string texto = (i + 1).ToString() + " - " + DateTime.Now.Year;
                        string valor = (i + 1).ToString() + DateTime.Now.Year;
                        ListaItemsPeriodos = new SelectListItem { Text = texto, Value = valor };
                        newList.Add(ListaItemsPeriodos);
                    }

                    List<SelectListItem> ListaEmpresas = new List<SelectListItem>();

                   
                    ListaEmpresas = new SelectList(db.com_empresas, "IdEmpresa", "strNombreEmpresa").ToList();

                   

                    ViewBag.BagPeriodos = new SelectList(newList, "Value", "Text");

                    ViewBag.BagEmpresas = new SelectList(ListaEmpresas, "Value", "Text");

                    return View();
                }
                else
                {
                    return View("~/Views/Home/Login.cshtml");
                }
            }
        }

        public ActionResult GetBuscaFacturas(string stringFacturas)
        {
            //stringFacturas = stringFacturas.Replace(',', '_');
            //stringFacturas = stringFacturas.Replace(';', '_');
            try
            {
                var query = (from p in db.csp_ConsultaStatusFacturas(stringFacturas) select new FacturasStatus() { FACTURA = p.FACTURA, DOCNUMBR = p.DOCNUMBR, ESTADO = p.ESTADO, ADEUDO_DECIMAL = p.ADEUDO_DECIMAL, PERIODO_PAGADO = p.PERIODO_PAGADO, CONCEPTOS_COMISIONBLES = Convert.ToInt32(p.CONCEPTOS_COMISIONABLES), CANCELADA = p.CANCELADA, COMISIONADA = p.COMISIONADA, PERIODO = p.PERIODO, CONCEPTOS = p.CONCEPTOS, FECHA = p.FECHA}).ToList();
                if (query.Count > 0)
                {
                    ViewBag.Facturas = query;
                }
                else
                {
                    ViewBag.Facturas = null;
                }
                ViewBag.CadenaFacturas = stringFacturas;

                return View(query);
            }
            catch(Exception ex)
            {
                var a = ex;
            }
           
            
            return View();
        }

        public ActionResult DetallesComisionada(String factura, String periodo)
        {
            ViewBag.strFactura = factura;
            ViewBag.strPeriodo = periodo;
            return PartialView();
        }

        public ActionResult DetallesConceptos(String conceptos)
        {
            ViewBag.strConceptos = conceptos;
            return PartialView();
        }

        public ActionResult DetallesPagada(String pagada, String fecha, String monto)
        {
            ViewBag.strPagada = pagada;
            ViewBag.strFecha = DateTime.Parse(fecha).ToShortDateString();
            ViewBag.strMonto = monto;
            return PartialView();
        }

        public ActionResult getCliente(string id_empresa)
        {
            string strCadenaEmpresa = "";

            List<RM00101> mtdListarPorEmpresa;

            strCadenaEmpresa = Utilidades.Utilidades.mtdRecuperaCadenaConexion(Convert.ToInt32(id_empresa));

            try
            {
                using (var ctx = new ELIEntities(strCadenaEmpresa))
                {
                    mtdListarPorEmpresa = ctx.RM00101.ToList();
                }
            }
            catch (Exception ex)
            {
                Console.Write(ex.ToString());
                throw new Exception("Error al obtener la lista", ex);
            }

            var Cliente = new SelectList(ListaPersonalizadaClientes(strCadenaEmpresa), "Value", "Text");
            return Json(new { error = false, Cliente = Cliente }, JsonRequestBehavior.AllowGet);
        }

        public SelectList ListaPersonalizadaClientes(string strCadenaEmpresa)
        {
            ELIEntities dbContext = new ELIEntities();
            var clientes = dbContext.RM00101.Select(x => new SelectListItem
            {
                Value = x.CUSTNMBR.Trim(),
                Text = x.CUSTNAME.Trim()
            });
            return new SelectList(clientes, "Value", "Text");
        }

        public SelectList ListaPersonalizadaVendedores()
        {
            var vendedores = db.com_vendedores.Where(p => p.boolActivo == true).Select(x => new SelectListItem
            {
                Value = x.idCodigoVendedor.ToString(),
                Text = x.strNombre.Trim() + " " + x.strApellidoP.Trim() + " " + x.strApellidoM.Trim()
            });
            return new SelectList(vendedores, "Value", "Text");
        }

        public SelectList ListaPersonalizadaVendedor()
        {
            var usuario = Session["UserID"];
            int codigousuario = int.Parse(string.Format("{0}", usuario));
            var codVendedor = db.com_UsuarioVendedor.Where(s => s.Id_Usuario == codigousuario).Select(a => a.idCodigoVendedor).FirstOrDefault();
            int codigovendedor = int.Parse(string.Format("{0}", codVendedor));
            var vendedores = db.com_vendedores.Where(p => p.idCodigoVendedor == codigovendedor).Select(x => new SelectListItem
            {
                Value = x.idCodigoVendedor.ToString(),
                Text = x.strNombre.Trim() + " " + x.strApellidoP.Trim() + " " + x.strApellidoM.Trim()
            });
            return new SelectList(vendedores, "Value", "Text");
        }

        // GET: Consultas/ClienteVendedor/
        [HttpGet]
        public ActionResult ClienteVendedor()
        {
            if (Session["RolID"] == null)
            {
                return View("~/Views/Home/Login.cshtml");
            }
            else
            {
                if (Session["RolID"].Equals("Administrador") || Session["RolID"].Equals("Operador"))
                {

                    return PartialView("ClienteVendedor");
                }
                else
                {
                    return View("~/Views/Home/Login.cshtml");
                }

            }
        }

        // POST: Consultas/generarCatalogoClienteVendedor/
        [HttpPost]
        public ActionResult generarCatalogoClienteVendedor(int codigoVendedor)
        {
            string spEjecutar = "csp_GeneraClienteVendedor";
            
            List<clienteVendedor> lista_vendedores = new List<clienteVendedor>();

            try
            {

                var Parameter1 = new SqlParameter
                {
                    ParameterName = "codigoVendedor",
                    Value = codigoVendedor
                };
                
                using (var ctx = new COMISIONESEntities())

                {
                    var query = ctx.Database.SqlQuery<clienteVendedor>("exec " + spEjecutar + " @codigoVendedor", Parameter1).ToList();

                    foreach (clienteVendedor datos_tabla in query)
                    {//lleno la lista
                        
                        lista_vendedores.Add(new clienteVendedor
                        {
                            idEmpresa = datos_tabla.idEmpresa,
                            idCliente = datos_tabla.idCliente,

                            strNombreCliente = datos_tabla.strNombreCliente,

                            intDiasCredito = datos_tabla.intDiasCredito,

                            intDiasRetencion = datos_tabla.intDiasRetencion,
                            intDiasGracia = datos_tabla.intDiasGracia,
                            idCodigoVendedor = datos_tabla.idCodigoVendedor,
                            nombreVendedor = datos_tabla.nombreVendedor
                        });

Comisionesv2/WebApplication1/Views/Consultas/ClienteVendedor.cshtml

@{
    ViewBag.Title = "Catálogo Cliente-Vendedor";
}

<div class="main-content">
    <div class="main-content-inner">

        <div class="page-content">

            <div class="page-header">
                <h1>
                    Catálogo Cliente-Vendedor
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Comisiones
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="widget-box">

                        <div class="widget-body">
                            <div class="widget-main">
                                <div id="fuelux-wizard-container">
                                    @*<hr />*@
                                    <div class="step-content pos-rel">
                                        <div class="step-pane active" data-step="1">

                                            <form class="form-horizontal" id="resumen-form" method="get">

                                                @using (Html.BeginForm())
                                                {

                                                    @Html.AntiForgeryToken()

                                                    <div class="form-group"></div>

                                                    <div id="div_ClienteVendedor" style="overflow-x: auto; overflow-y: auto; ">


                                                    </div>
                                                }

                                            </form>



                                        </div>


                                    </div>
                                </div>

                                <hr />

                            </div><!-- /.widget-main -->
                        </div><!-- /.widget-body -->
                    </div>



                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="@Url.Content("~/assets/js/jquery.js")"></script>
<script src="@Url.Content("~/assets/js/bootstrap.js")"></script>
<script src="@Url.Content("~/assets/js/select2.js")"></script>

<script src="@Url.Content("~/assets/js/fuelux/fuelux.wizard.js")"></script>
<script src="@Url.Content("~/assets/js/ace/elements.wizard.js")"></script>

<script src="@Url.Content("~/assets/js/jquery.maskedinput.js")"></script>
<script src="@Url.Content("~/assets/js/moment.min.js")"></script>
<script src="@Url.Content("~/assets/js/daterangepicker.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
<script src="@Url.Content("~/assets/js/bootbox.js")"></script>




Comisionesv2/WebApplication1/Views/Consultas/DetallesComisionada.cshtml
<div>La factura <b>@ViewBag.strFactura</b> fué comisionada en el periodo <b>@ViewBag.strPeriodo</b></div>

Comisionesv2/WebApplication1/Views/Consultas/DetallesConceptos.cshtml
<div>Se cuenta con los siguientes conceptos comisionables: <b>@ViewBag.strConceptos</b></div>

Comisionesv2/WebApplication1/Views/Consultas/DetallesPagada.cshtml
@if (ViewBag.strPagada == "PAGADA")
{
    <div>La fecha de pago de factura fué: <b>@ViewBag.strFecha</b>
    </div>
}
else
{
    <div>Se debe la cantidad de: <b>$@ViewBag.strMonto</b></div>
}


Comisionesv2/WebApplication1/Views/Consultas/GetBuscaFacturas.cshtml
@model IEnumerable<OneCoreData.FacturasStatus>

@{
    Layout = null;
}

<div class="widget-body">
    @foreach (var item in Model)
    {

        if (item.DOCNUMBR != null)
        {
            <div class="profile-activity clearfix">
                @if (item.COMISIONADA.Equals("COMISIONADA"))
                {
                    <i class="pull-left thumbicon fa fa-check btn-success no-hover"></i>
                    <own>La factura </own>
                    <b>@item.FACTURA</b>
                    <own>se encuentra comisionada.</own>
                    <button class="btn btn-primary btn-sm pull-right" id="btnDetalleComisionada" onclick="llamarVistaParcial('@item.FACTURA','@item.PERIODO')" data-toggle="modal" data-target="#myModal">
                        <i class="ace-icon fa  fa-archive bigger-125"></i>
                        Ver Detalle
                    </button>
                }
                else
                {
                    <i class="pull-left thumbicon fa fa-remove btn-danger no-hover"></i>
                    <own>La factura </own>
                    <b>@item.FACTURA</b>
                    <own>se encuentra comisionada.</own>
                }
            </div>

            <div class="profile-activity clearfix">
                @if (item.ESTADO.Equals("PAGADA"))
                {
                    <i class="pull-left thumbicon fa fa-check btn-success no-hover"></i>
                    <own>La factura </own>
                    <b>@item.FACTURA</b>
                    <own>se encuentra totalmente pagada.</own>
                    <button class="btn btn-primary btn-sm pull-right" id="btnDetallePagada" onclick="llamarVistaPagada('@item.ESTADO','@item.FECHA','@item.ADEUDO_DECIMAL')" data-toggle="modal" data-target="#myModal">
                        <i class="ace-icon fa  fa-archive bigger-125"></i>
                        Ver Detalle
                    </button>

                }
                else
                {
                    <i class="pull-left thumbicon fa fa-remove btn-danger no-hover"></i>
                    <own>La factura </own>
                    <b>@item.FACTURA</b>
                    <own>se encuentra totalmente pagada.</own>
                    <button class="btn btn-primary btn-sm pull-right" id="btnDetalleNoPagada" onclick="llamarVistaPagada('@item.ESTADO','@item.FECHA','@item.ADEUDO_DECIMAL')" data-toggle="modal" data-target="#myModal">
                        <i class="ace-icon fa  fa-archive bigger-125"></i>
                        Ver Detalle
                    </button>
                }
            </div>

            <div class="profile-activity clearfix">
                @if (item.CONCEPTOS_COMISIONBLES > 0)
                {
                    <i class="pull-left thumbicon fa fa-check btn-success no-hover"></i>
                    <own>La factura </own>
                    <b>@item.FACTURA</b>
                    <own>cuenta con conceptos comisionables.</own>
                    <button class="btn btn-primary btn-sm pull-right" id="btnDetalleComisionada" onclick="llamarVistaConceptos('@item.CONCEPTOS')" data-toggle="modal" data-target="#myModal">
                        <i class="ace-icon fa  fa-archive bigger-125"></i>
                        Ver Detalle
                    </button>
                }
                else
                {
                    <i class="pull-left thumbicon fa fa-remove btn-danger no-hover"></i>
                    <own>La factura </own>
                    <b>@item.FACTURA</b>
                    <own>cuenta con conceptos comisionables.</own>
                }
            </div>

            <div class="profile-activity clearfix">
                @if (item.CANCELADA.Equals("SI"))
                {
                    <i class="pull-left thumbicon fa fa-check btn-success no-hover"></i>
                    <own>La factura </own>
                    <b>@item.FACTURA</b>
                    <own>se encuentra cancelada.</own>
                }
                else
                {
                    <i class="pull-left thumbicon fa fa-remove btn-danger no-hover"></i>
                    <own>La factura </own>
                    <b>@item.FACTURA</b>
                    <own>se encuentra cancelada.</own>
                }
            </div>
        }
        else
        {
            <div class="profile-activity clearfix">
                <i class="pull-left thumbicon fa fa-bug btn-danger no-hover"></i>
                <own>La factura </own>
                <b>@item.FACTURA</b>
                <own>no ha sido encontrada en el sistema. </own>
            </div>
        }


    }
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" role ="dialog">
<div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="hide" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Detalle.</h4>
        </div>
        <div class="modal-body">
            <div id="resultado"></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-success" onclick="cerrarModal();">Cerrar</button>
        </div>
    </div>
</div>
    </div>

<script>
    $('[data-rel=popover]').popover({ html: true });
</script>

<script>

    function cerrarModal() {
        $('#myModal').modal('hide');
    }


</script>


<script>
    function llamarVistaParcial(factura, periodo) {
        var laURLDeLaVista = '@Url.Action("DetallesComisionada", "Consultas")' + '?factura=' + factura + '&periodo=' + periodo;
        $.ajax({
            cache: false,
            async: true,
            type: "POST",
            url: laURLDeLaVista,
            data: {},
            success: function(response) {
                $('#resultado').html('');
                $('#resultado').html(response);
            }
        });
    }
</script>

<script>
    function llamarVistaPagada(pagada, fecha, monto) {
        var laURLDeLaVista = '@Url.Action("DetallesPagada", "Consultas")' + '?pagada=' + pagada + '&fecha=' + fecha + '&monto=' + monto;
        $.ajax({
            cache: false,
            async: true,
            type: "POST",
            url: laURLDeLaVista,
            data: {},
            success: function(response) {
                $('#resultado').html('');
                $('#resultado').html(response);
            }
        });
    }
</script>

<script>
    function llamarVistaConceptos(conceptos) {
        var laURLDeLaVista = '@Url.Action("DetallesConceptos", "Consultas")' + '?conceptos=' + conceptos;
        $.ajax({
            cache: false,
            async: true,
            type: "POST",
            url: laURLDeLaVista,
            data: {},
            success: function (response) {
                $('#resultado').html('');
                $('#resultado').html(response);
            }
        });
    }
</script>


@*@section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }


        <script src="~/assets/js/jquery.js"></script>
        <script src="~/assets/js/bootstrap.js"></script>
        <script src="~/assets/js/select2.js"></script>

        <script src="~/assets/js/fuelux/fuelux.wizard.js"></script>
        <script src="~/assets/js/ace/elements.wizard.js"></script>

        <script src="~/assets/js/jquery.maskedinput.js"></script>
        <script src="~/assets/js/moment.min.js"></script>
        <script src="~/assets/js/daterangepicker.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/assets/js/bootbox.js"></script>*@

    @*Cargado desde vista parcial con @ViewBag.CadenaFacturas*@

Comisionesv2/WebApplication1/Views/Consultas/ReporteComisionesCliente.cshtml

@{
    ViewBag.Title = "Reporte de Comisiones por Cliente";
}

<div class="main-content">
    <div class="main-content-inner">

        <div class="page-content">

            <div class="page-header">
                <h1>
                    Reporte de Comisiones por Cliente
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Comisiones
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="widget-box">

                        <div class="widget-body">
                            <div class="widget-main">
                                <div id="fuelux-wizard-container">
                                    @*<hr />*@
                                    <div class="step-content pos-rel">
                                        <div class="step-pane active" data-step="1">

                                            <form class="form-horizontal" id="resumen-form" method="get">

                                                @using (Html.BeginForm())
                                                {

                                                    @Html.AntiForgeryToken()

                                                    <div class="form-group"></div>

                                                    <div id="div_ComisionesCliente" style="overflow-x: auto; overflow-y: auto; ">


                                                    </div>
                                                }

                                            </form>



                                        </div>


                                    </div>
                                </div>

                                <hr />

                            </div><!-- /.widget-main -->
                        </div><!-- /.widget-body -->
                    </div>



                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script src="~/assets/js/jquery.js"></script>
<script src="~/assets/js/bootstrap.js"></script>
<script src="~/assets/js/select2.js"></script>

<script src="~/assets/js/fuelux/fuelux.wizard.js"></script>
<script src="~/assets/js/ace/elements.wizard.js"></script>

<script src="~/assets/js/jquery.maskedinput.js"></script>
<script src="~/assets/js/moment.min.js"></script>
<script src="~/assets/js/daterangepicker.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/assets/js/bootbox.js"></script>



Comisionesv2/WebApplication1/Views/Consultas/ReportePeriodoAnterior.cshtml

@{
    ViewBag.Title = "Reporte de Periodos Anteriores";
}

<div class="main-content">
    <div class="main-content-inner">

        <div class="page-content">

            <div class="page-header">
                <h1>
                    Reporte de Periodos Anteriores
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Comisiones
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="widget-box">

                        <div class="widget-body">
                            <div class="widget-main">
                                <div id="fuelux-wizard-container">
                                    @*<hr />*@
                                    <div class="step-content pos-rel">
                                        <div class="step-pane active" data-step="1">

                                            <form class="form-horizontal" id="resumen-form" method="get">

                                                @using (Html.BeginForm())
                                                {

                                                    @Html.AntiForgeryToken()

                                                    <div class="form-group"></div>

                                                    <div id="div_ReportePeriodoAnterior" style="overflow-x: auto; overflow-y: auto; ">


                                                    </div>
                                                }

                                            </form>



                                        </div>


                                    </div>
                                </div>

                                <hr />

                            </div><!-- /.widget-main -->
                        </div><!-- /.widget-body -->
                    </div>



                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="@Url.Content("~/assets/js/jquery.js")"></script>
<script src="@Url.Content("~/assets/js/bootstrap.js")"></script>
<script src="@Url.Content("~/assets/js/select2.js")"></script>

<script src="@Url.Content("~/assets/js/fuelux/fuelux.wizard.js")"></script>
<script src="@Url.Content("~/assets/js/ace/elements.wizard.js")"></script>

<script src="@Url.Content("~/assets/js/jquery.maskedinput.js")"></script>
<script src="@Url.Content("~/assets/js/moment.min.js")"></script>
<script src="@Url.Content("~/assets/js/daterangepicker.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
<script src="@Url.Content("~/assets/js/bootbox.js")"></script>

Comisionesv2/WebApplication1/Views/Consultas/ResumenComisionesVendedor.cshtml
@{
    ViewBag.Title = "Resumen de Comisiones por Vendedor";
}

<div class="main-content">
    <div class="main-content-inner">

        <div class="page-content">

            <div class="page-header">
                <h1>
                    Resumen de Comisiones por Vendedor
                    <small>
                        <i class="ace-icon fa fa-angle-double-right"></i>
                        Comisiones
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="widget-box">

                        <div class="widget-body">
                            <div class="widget-main">
                                <div id="fuelux-wizard-container">
                                    @*<hr />*@
                                    <div class="step-content pos-rel">
                                        <div class="step-pane active" data-step="1">

                                            <form class="form-horizontal" id="resumen-form" method="get">

                                                @using (Html.BeginForm())
                                                {

                                                    @Html.AntiForgeryToken()

                                                    <div class="form-group"></div>

                                                    <div id="div_ResumenComisionesVendedor" style="overflow-x: auto; overflow-y: auto; ">


                                                    </div>
                                                }

                                            </form>



                                        </div>


                                    </div>
                                </div>

                                <hr />

                            </div><!-- /.widget-main -->
                        </div><!-- /.widget-body -->
                    </div>



                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script src="~/assets/js/jquery.js"></script>
<script src="~/assets/js/bootstrap.js"></script>
<script src="~/assets/js/select2.js"></script>

<script src="~/assets/js/fuelux/fuelux.wizard.js"></script>
<script src="~/assets/js/ace/elements.wizard.js"></script>

<script src="~/assets/js/jquery.maskedinput.js"></script>
<script src="~/assets/js/moment.min.js"></script>
<script src="~/assets/js/daterangepicker.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/assets/js/bootbox.js"></script>
